# Default values for my-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

backend:
  image: nishant234/backend:latest
  replicas: 1
  port: 5000
  env:
    MONGODB_URI: "mongodb://mongo-service:27017/wanderlust"

frontend:
  image: nishant234/frontend
  replicas: 1
  port: 5173
  nodePort: 30001
  env:
    VITE_API_PATH: "http://backend:5000"

mongo:
  image: mongo
  replicas: 1
  port: 27017

